### ISSUE TITLE
Jellyneo search is searching for wrong title

### ISSUE THREAD

**Issue by katiejwarren** [diceroll123/NeoSearchHelper#4]
Whenever I click on the Jellyneo item database check icon, "%20" appears between each word. For example, if I've clicked the icon underneath a Bitten Red Apple, the Jellyneo search box searches for "Bitten%20Red%20Apple." I've tried uninstalling and reinstalling and it only does it for the Jellyneo search. Is it just my computer?

**Comment by diceroll123** [comment]
I definitely fixed this last night, when it started.

You may have to manually update the code. Copy and paste, etc. The Raw button doesn't like to update sometimes.
