### ISSUE TITLE
Adding icons to Employment agency job page (idea?)

### ISSUE THREAD

**Issue by nbremer** [diceroll123/NeoSearchHelper#7]
Hi! 

Thank you very much for making this user script, it's been such a great help! :)

Here is just an idea, but I enjoy doing a few Faerieland Employment Agency jobs every now and then, and this script only adds the icons after you accepted a job (on the job page), but I could very much use them on the job listing page as well. I therefore fiddled in your code around until I got it working there too and thought it might be useful to share :)

I have no experience with user scripts, and very little with jQuery, so apologies if this is not very "elegantly" coded.

I added the following link to the top:
```js
// @match      http://www.neopets.com/faerieland/employ/employment.phtml?type=jobs&voucher=basic*
```

And then adjusted the Employment Agency code to:
```js
// employment agency
if(document.URL.indexOf("employment") != -1) {
    if(document.URL.indexOf("type=jobs") != -1) {
        $("b:contains('Find')").each(function(k,v) {
            itemname = $(v).parent().clone().find("b").remove().end().html().split("<br>")[0];
            $(v).after(makelinks(itemname));
        });
    } else {
        $("b:contains('Find')").eq(0).after(makelinks($("b:contains('Find')").eq(0).justtext()));
    }
}
```

PS. I also saw that if you go to your shop stock by clicking on the "Close and View Stock" in the pop-up of an item that you've just added to your shop that the URL is different. I therefore also added `// @match      http://www.neopets.com/market_your.phtml*` as a link to the top and then added `|| document.URL.indexOf("market_your") != -1` to the Shop section :)

**Comment by diceroll123** [comment]
Quite long overdue, but I've added the suggested changes. 👍🏽 Thanks!
